import { type NextRequest, NextResponse } from "next/server";
import { generateObject } from "ai";
import { geminiFlash } from "@/lib/ai/gemini";
import { db } from "@/lib/db";
import { lessonRecallNodes } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { z } from "zod";

// ─── Do NOT add: edge runtime — needs pg (nodejs) driver ────────────────────
export const runtime = "nodejs";

// ─── Request Payload Types ────────────────────────────────────────────────────

export interface TheoryAnswer {
  /** Unique question identifier generated by the exam generator (e.g. 'q1') */
  questionId: string;
  /** The full question text as shown to the student */
  questionText: string;
  /** Model sample answer stored with the generated exam */
  sampleAnswer: string;
  /**
   * Granular rubric items from the generated exam, each carrying a concept key
   * that maps to a recall node so we can update mastery afterwards.
   */
  gradingCriteria: {
    criterion: string;
    maxPoints: number;
    /** Optional: recall node key this criterion tests */
    targetConceptKey?: string;
  }[];
  /** The student's raw free-text answer */
  userAnswer: string;
  /** Total marks allocated to this question */
  maxMarks: number;
}

export interface SandboxTestResult {
  /** lessonChallenge id */
  challengeId: string;
  language: "python" | "javascript";
  /** true when all test-suite assertions passed */
  passed: boolean;
  /** Number of test cases that passed */
  passedCount: number;
  /** Total test cases */
  totalCount: number;
}

// ─── Output Types ─────────────────────────────────────────────────────────────

/** AI-graded result for a single theory question */
export interface TheoryQuestionResult {
  questionId: string;
  questionText: string;
  maxMarks: number;
  earnedMarks: number;
  /** 0–100 normalised score */
  score: number;
  isPassed: boolean;
  /** Clear breakdown of what was missed or misunderstood */
  critique: string;
  /** Exact key matching a record in lesson_recall_nodes */
  targetedConceptKey: string;
  rubricBreakdown: {
    criterion: string;
    passed: boolean;
    feedback: string;
  }[];
}

/** Sandbox result enriched with a score for the diagnostics view */
export interface ChallengeResult extends SandboxTestResult {
  /** 0–100 score derived from passedCount / totalCount */
  score: number;
  isPassed: boolean;
}

export interface EvaluationResponse {
  lessonId: string;
  theoryResults: TheoryQuestionResult[];
  challengeResults: ChallengeResult[];
  summary: {
    theoryScore: number;
    challengeScore: number;
    overallScore: number;
    overallGrade: string;
    totalTheoryMarks: number;
    earnedTheoryMarks: number;
  };
  /** Mastery updates written to user_error_memory (optimistic) */
  masteryUpdates: {
    conceptKey: string;
    newScore: number;
    direction: "improved" | "declined" | "unchanged";
  }[];
}

// ─── Zod Schema for Gemini Output ─────────────────────────────────────────────

const QuestionGradingSchema = z.object({
  score: z
    .number()
    .int()
    .min(0)
    .max(100)
    .describe("Overall percentage score 0–100 for this answer"),
  isPassed: z
    .boolean()
    .describe("True when the student scored ≥ 60% on this question"),
  critique: z
    .string()
    .describe(
      "Concise, constructive breakdown: what key ideas were missing or misunderstood. Maximum 3 sentences."
    ),
  targetedConceptKey: z
    .string()
    .describe(
      "The camelCase key of the lesson recall node that this question most directly tests (must match a key from the provided recall node list)"
    ),
  rubricBreakdown: z
    .array(
      z.object({
        criterion: z.string(),
        passed: z.boolean(),
        feedback: z
          .string()
          .describe("One sentence specific to this criterion"),
      })
    )
    .describe("One entry per rubric criterion, in the same order as provided"),
});

const BatchGradingResponseSchema = z.object({
  results: z
    .array(QuestionGradingSchema)
    .describe(
      "One graded entry per question, in the same order as the input list"
    ),
});

// ─── Helpers ──────────────────────────────────────────────────────────────────

function deriveGrade(pct: number): string {
  if (pct >= 90) return "A*";
  if (pct >= 80) return "A";
  if (pct >= 70) return "B";
  if (pct >= 60) return "C";
  if (pct >= 50) return "D";
  return "U";
}

/**
 * Computes a 0–100 score from sandbox results, guarding against division by zero.
 */
function challengeScore(r: SandboxTestResult): number {
  if (!r.totalCount || r.totalCount === 0) return r.passed ? 100 : 0;
  return Math.round((r.passedCount / r.totalCount) * 100);
}

// ─── Route Handler ─────────────────────────────────────────────────────────────

export async function POST(req: NextRequest): Promise<NextResponse> {
  try {
    const body = (await req.json()) as {
      lessonId: string;
      theoryAnswers: TheoryAnswer[];
      sandboxResults: SandboxTestResult[];
    };

    const { lessonId, theoryAnswers = [], sandboxResults = [] } = body;

    if (!lessonId) {
      return NextResponse.json(
        { error: "lessonId is required" },
        { status: 400 }
      );
    }

    // ── 1. Fetch recall nodes for rubric context ─────────────────────────────
    const recallNodes = await db.query.lessonRecallNodes.findMany({
      where: eq(lessonRecallNodes.lessonId, lessonId),
    });

    const recallNodeSummary = recallNodes
      .map((n) => `- key: "${n.key}" | type: ${n.nodeType} | summary: ${n.summary}`)
      .join("\n");

    // ── 2. Grade theory answers in one Gemini call ───────────────────────────
    let theoryResults: TheoryQuestionResult[] = [];

    if (theoryAnswers.length > 0) {
      const questionsBlock = theoryAnswers
        .map((q, idx) => {
          const rubricLines = q.gradingCriteria
            .map(
              (c) =>
                `  - ${c.criterion} (${c.maxPoints} pts)${c.targetConceptKey ? ` [concept: ${c.targetConceptKey}]` : ""}`
            )
            .join("\n");

          return `### Question ${idx + 1} [id: ${q.questionId}]
Question: ${q.questionText}
Max Marks: ${q.maxMarks}
Sample Answer: ${q.sampleAnswer}
Grading Rubric:
${rubricLines}
Student Answer: ${q.userAnswer || "(No answer provided)"}`;
        })
        .join("\n\n---\n\n");

      const gradingPrompt = `You are a rigorous university-level computer science examiner.

Grade the following ${theoryAnswers.length} student answer(s). For each question:
- Compare carefully against the model sample answer and rubric.
- Assign a \`score\` (0–100) proportional to rubric coverage.
- Set \`isPassed\` to true if score ≥ 60.
- Write a concise \`critique\` (≤ 3 sentences) citing specific omissions.
- Identify the \`targetedConceptKey\` from the lesson recall nodes below that this question most directly tests.
- Provide a \`rubricBreakdown\` with one entry per rubric criterion.

Lesson Recall Nodes (for targetedConceptKey reference):
${recallNodeSummary || "(No recall nodes found — make a best-effort key guess in camelCase)"}

Questions to grade:
${questionsBlock}

Return exactly ${theoryAnswers.length} result(s) in the \`results\` array, in the same order as the questions above.`;

      const { object: gradingResponse } = await generateObject({
        model: geminiFlash,
        schema: BatchGradingResponseSchema,
        prompt: gradingPrompt,
        system:
          "You are a professional academic examiner. Grade submissions fairly, strictly, and constructively. Never inflate scores. Be specific about what was missing.",
      });

      theoryResults = gradingResponse.results.map((result, idx) => {
        const q = theoryAnswers[idx];
        const earnedMarks =
          q.maxMarks > 0 ? Math.round((result.score / 100) * q.maxMarks) : 0;
        return {
          questionId: q.questionId,
          questionText: q.questionText,
          maxMarks: q.maxMarks,
          earnedMarks,
          score: result.score,
          isPassed: result.isPassed,
          critique: result.critique,
          targetedConceptKey: result.targetedConceptKey,
          rubricBreakdown: result.rubricBreakdown,
        };
      });
    }

    // ── 3. Enrich sandbox results ────────────────────────────────────────────
    const challengeResults: ChallengeResult[] = sandboxResults.map((r) => {
      const score = challengeScore(r);
      return { ...r, score, isPassed: score >= 60 };
    });

    // ── 4. Compute summary statistics ────────────────────────────────────────
    const totalTheoryMarks = theoryResults.reduce(
      (sum, r) => sum + r.maxMarks,
      0
    );
    const earnedTheoryMarks = theoryResults.reduce(
      (sum, r) => sum + r.earnedMarks,
      0
    );
    const theoryScore =
      totalTheoryMarks > 0
        ? Math.round((earnedTheoryMarks / totalTheoryMarks) * 100)
        : 0;

    const avgChallengeScore =
      challengeResults.length > 0
        ? Math.round(
            challengeResults.reduce((sum, r) => sum + r.score, 0) /
              challengeResults.length
          )
        : 0;

    // Weighted: theory 70%, challenges 30% (challenges optional)
    const hasChallenge = challengeResults.length > 0;
    const overallScore = hasChallenge
      ? Math.round(theoryScore * 0.7 + avgChallengeScore * 0.3)
      : theoryScore;

    // ── 5. Compute mastery direction for each concept ────────────────────────
    const masteryUpdates: EvaluationResponse["masteryUpdates"] = theoryResults.map(
      (result) => {
        let newScore: number;
        let direction: "improved" | "declined" | "unchanged";

        if (result.score >= 86) {
          // Strong pass — signal topic absorption (capped at 100)
          newScore = Math.min(100, 75 + Math.round((result.score - 86) * 2));
          direction = "improved";
        } else if (result.score < 70) {
          // Failure — drop mastery, log error context
          newScore = Math.max(0, Math.round(result.score * 0.6));
          direction = "declined";
        } else {
          // Borderline pass — no change
          newScore = 50;
          direction = "unchanged";
        }

        return { conceptKey: result.targetedConceptKey, newScore, direction };
      }
    );

    const response: EvaluationResponse = {
      lessonId,
      theoryResults,
      challengeResults,
      summary: {
        theoryScore,
        challengeScore: avgChallengeScore,
        overallScore,
        overallGrade: deriveGrade(overallScore),
        totalTheoryMarks,
        earnedTheoryMarks,
      },
      masteryUpdates,
    };

    return NextResponse.json(response);
  } catch (err: unknown) {
    const message =
      err instanceof Error ? err.message : "Internal Server Error";
    console.error("[/api/exam/evaluate] Error:", err);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
